// Generated by CozyScript 0.1.1
(function() {
  var assert;

  assert = require('assert');

  describe('Ubike', function() {
    describe('#request()', function() {
      return it('should return xml document withour error', function() {
        var Ubike, ubike;
        Ubike = require('../ubike');
        ubike = new Ubike.Ubike;
        return ubike.request();
      });
    });
    return describe('#search()', function() {
      return it('should return correct station object', function(done) {
        var Ubike, ubike;
        Ubike = require('../ubike');
        ubike = new Ubike.Ubike;
        return ubike.request(function() {
          assert.strictEqual(ubike.search('台北市政府')['name'], '台北市政府');
          return done();
        });
      });
    });
  });

}).call(this);
